# Generated by Django 4.0.5 on 2022-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantekaapp', '0002_reportcategory_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='small_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
