# Generated by Django 4.0.5 on 2022-09-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantekaapp', '0005_remove_report_category_report_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='reports', to='quantekaapp.reportcategory'),
        ),
    ]
